# Generated by Django 2.0.1 on 2018-11-05 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Students',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('stu_id', models.CharField(max_length=20)),
                ('sex', models.CharField(max_length=20)),
                ('tel', models.CharField(max_length=20)),
                ('academy', models.CharField(max_length=40)),
                ('score1', models.FloatField(null=True)),
                ('audition1', models.TextField(null=True)),
                ('score2', models.FloatField(null=True)),
                ('audition2', models.TextField(null=True)),
                ('score3', models.FloatField(null=True)),
                ('audition3', models.TextField(null=True)),
            ],
        ),
    ]
